name: Push to main
on:
  push:
    branches:
      - main
permissions:
  contents: write  # Allows write access to repository content
  issues: write    # Allows write access to issues (if needed)
  pull-requests: write  # Allows write access to pull requests (if needed)

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install Trestle
      run: bash scripts/automation/install_trestle.sh
    - name: Release
      run: source scripts/automation/release.sh
    - name: Push the changes
      run: bash scripts/automation/push.sh
  downstream-repo-update-cd:
    name: Update downstream repository - cd
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: Clone branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main
        token: ${{ secrets.PUSH_TOKEN }}
    - name: Clone downstream repo
      uses: actions/checkout@v4
      with:
        repository: oscal-compass/e2e-demo-cd
        path: './e2e-demo-cd'
        token: ${{ secrets.PUSH_TOKEN }}
        fetch-depth: 0
    - name: Update component definitions
      run: bash scripts/automation/update_cd.sh
      env:
        GH_TOKEN: ${{ secrets.PUSH_TOKEN }}
  downstream-repo-update-ssp:
    name: Update downstream repository - ssp
    runs-on: ubuntu-latest
    needs: release
    steps:
    - name: Clone branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: main
        token: ${{ secrets.PUSH_TOKEN }}
    - name: Clone downstream repo
      uses: actions/checkout@v4
      with:
        repository: oscal-compass/e2e-demo-ssp
        path: './e2e-demo-ssp'
        token: ${{ secrets.PUSH_TOKEN }}
        fetch-depth: 0
    - name: Update ssp
      run: bash scripts/automation/update_ssp.sh
      env:
        GH_TOKEN: ${{ secrets.PUSH_TOKEN }}
  merge-main-to-develop:
    name: Merge main to develop
    runs-on: ubuntu-latest
    needs: release
    concurrency: 
      group: ${{ github.ref }}-${{ github.workflow }}-${{ github.job }}-main
      cancel-in-progress: true
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: main
        target-branch: develop
        commit-message: "chore: Merge back version tags and changelog into develop."
